/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Deer.glb -T 
Files: Deer.glb [517KB] > F:\My Documents\Sites games\memory-game\public\models\Deer-transformed.glb [517KB] (0%)
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function ModelDeer(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('models/Deer-transformed.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="AnimalArmature">
          <primitive object={nodes.Body} />
          <primitive object={nodes.IKBackLegL} />
          <primitive object={nodes.IKFrontLegL} />
          <primitive object={nodes.IKBackLegR} />
          <primitive object={nodes.IKFrontLegR} />
        </group>
        <group name="Deer">
          <skinnedMesh name="Cube" geometry={nodes.Cube.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Cube.skeleton} />
          <skinnedMesh name="Cube_1" geometry={nodes.Cube_1.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Cube_1.skeleton} />
          <skinnedMesh name="Cube_2" geometry={nodes.Cube_2.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Cube_2.skeleton} />
          <skinnedMesh name="Cube_3" geometry={nodes.Cube_3.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Cube_3.skeleton} />
          <skinnedMesh name="Cube_4" geometry={nodes.Cube_4.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Cube_4.skeleton} />
          <skinnedMesh name="Cube_5" geometry={nodes.Cube_5.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Cube_5.skeleton} />
          <skinnedMesh name="Cube_6" geometry={nodes.Cube_6.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Cube_6.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('models/Deer-transformed.glb')
