/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 models\fence_planksDouble.glb --output output\fence_planksDouble.js --transform 
Files: models\fence_planksDouble.glb [11.16KB] > E:\Downloads\kenney_nature-kit\JSX\output\fence_planksDouble-transformed.glb [1.6KB] (86%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
const link = `${process.env.NEXT_PUBLIC_CDN}games/Assets/KennyNL/Nature/Models/fence_planksDouble-transformed.glb`;

export function ModelKennyNLNatureFencePlanksDouble(props) {
  const { nodes, materials } = useGLTF(link)
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.fence_planksDouble.geometry} material={materials.wood} position={[0, -0.05, 0]} />
    </group>
  )
}

useGLTF.preload(link)
